CREATE TABLE [dbo].[ItemSubItem3]
(
	[ItemId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Item](Id) NOT NULL,
	[SubItem3Id] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [SubItem3](Id) NOT NULL,
	PRIMARY KEY CLUSTERED ([ItemId], [SubItem3Id])
)